
#ifndef _HEADER_GRS_DEF_20080410
#define _HEADER_GRS_DEF_20080410

#define LOG_TYPE_SUCCESS 0
#define LOG_TYPE_FAILED  1
#define LOG_TYPE_WARRING 2
#define LOG_TYPE_NORMOL  3

#define YWEVT_UI_REDAY	1	//!< UI准备好的事件

#endif

